# ======== ======== ======== ======== ======== ========
#     ____             _   _     _
#    |  _ \  ___  __ _| |_| |__ | |    ___   __ _
#    | | | |/ _ \/ _` | __| '_ \| |   / _ \ / _` |
#    | |_| |  __/ (_| | |_| | | | |__| (_) | (_| |
#    |____/ \___|\__,_|\__|_| |_|_____\___/ \__, |
#                                           |___/
# ======== ======== ======== ======== ======== ========

message:
  death-message: "%s"
  last-words: "Last Words: %s"
  sound:
    type: "ENTITY_SLIME_JUMP"
    volume: 0.5
    pitch: 1.0

last-words:
  enabled: true
  commands: true
  messages: true
