name: DeathLog
version: '1.1.1'
main: io.github.math0898.deathlog.DeathLog
api-version: '1.21'
permissions:
  deathlog.reload:
    default: op
    description: "Required in order to reload the config."
